apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: eks-udacity-app
data:
  API_URL : http://af7805098b91848e59cb858fae815fd8-839165628.us-east-1.elb.amazonaws.com:3030
  NODE_ENV : production
  VERSION : '1'
  TYPEORM_CONNECTION : postgres
  TYPEORM_MIGRATIONS_DIR : ./src/migrations
  TYPEORM_ENTITIES : ./src/modules/domain/**/*.entity.ts
  TYPEORM_MIGRATIONS : ./src/migrations/*.ts

  TYPEORM_HOST : database-1.chv5qnm9nump.us-east-1.rds.amazonaws.com
  TYPEORM_PORT : '5432'
  TYPEORM_USERNAME : postgres
  TYPEORM_PASSWORD : mypassword
  TYPEORM_DATABASE : postgres



