# base image
FROM circleci/node:13.8.0
USER node
# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# RUN apk update && apk upgrade && \
#     apk add --no-cache bash git openssh

COPY . /usr/src/app/


RUN chown node:node /usr/src/app && \
    mkdir /.npm && chown node:node /.npm && \
    mkdir /.config && chown node:node /.config && \
    mkdir /.cache && chown node:node /.cache && \
    mkdir /.local && chown node:node /.local

USER node

RUN npm install
#RUN npx browserslist@latest --update-db
#RUN npm install --save-dev html-webpack-plugin@3
#RUN npm update
#RUN npm update
#RUN npm audit fix --audit-level=critical --force
#RUN npm audit fix --audit-level=critical --force
#RUN npm audit --audit-level=critical

#EXPOSE 3000
# start app
CMD ["npm", "run", "start"]
EXPOSE 3000