# base image
FROM circleci/node:13.8.0

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/root_modules/.bin` to $PATH
ENV PATH /usr/src/app/root_modules/.bin:$PATH

# copy the code
COPY . /usr/src/app/

# create a new user
RUN adduser --system --home /usr/src/app --no-create-home --shell /bin/false appuser && \
    chown -R appuser:appuser /usr/src/app && \
    mkdir /.npm /.config /.cache /.local && \
    chown -R appuser:appuser /.npm /.config /.cache /.local

# switch to the new user
USER appuser

RUN npm install

# start app
CMD ["npm", "run", "start"]
EXPOSE 3000
