# base image
FROM circleci/node:13.8.0
USER root
# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/root_modules/.bin` to $PATH
ENV PATH /usr/src/app/root_modules/.bin:$PATH

# copy the code
COPY . /usr/src/app/

# create a new user and group
RUN addgroup --system appgroup && \
    adduser --system --home /usr/src/app --no-create-home --shell /bin/false --ingroup appgroup appuser && \
    chown -R appuser:appgroup /usr/src/app && \
    mkdir /.npm /.config /.cache /.local && \
    chown -R appuser:appgroup /.npm /.config /.cache /.local

# switch to the new user
USER appuser

RUN npm install

# start app
CMD ["npm", "run", "start"]
EXPOSE 3000
