# docker-compose.yml
version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "3030:3030"
    image: huannv93/udacity-awsdevops-project03-1_backend #naming for image when docker-compose build
    networks:
      - "backend"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - "backend"
    depends_on:
      - "backend"
    image: huannv93/udacity-awsdevops-project03-1_frontend ##naming for image when docker-compose build
networks:
  backend:


