apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: eks-udacity-app
  labels:
    app: eks-udacity-app-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  eks-udacity-app-be
  template:
    metadata:
      labels:
        app: eks-udacity-app-be
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      
      containers:
      - name: be
        image: huannv93/udacity-awsdevops-project03-1_backend
        resources:
          requests:
            cpu: 500m
        ports:
        - name: http
          containerPort: 3030
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: eks-udacity-app
  labels:
    app: eks-udacity-app-be
spec:
  type: LoadBalancer
  selector:
    app:  eks-udacity-app-be
  ports:
      - port: 3030
        targetPort: 3030
        protocol: TCP