apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: eks-udacity-app
  labels:
    app: eks-udacity-app-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  eks-udacity-app-be
  template:
    metadata:
      labels:
        app: eks-udacity-app-be
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      
      containers:
      - name: be
        image: huannv93/udacity-awsdevops-project03-1_backend:126
        # resources:
        #   requests:
        #     cpu: 500m       
        ports:
        - name: http
          containerPort: 3030
        imagePullPolicy: IfNotPresent
        env:
         - name: NODE_ENV
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: NODE_ENV
         - name: VERSION
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: VERSION
         - name: TYPEORM_CONNECTION
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: TYPEORM_CONNECTION
         - name: TYPEORM_MIGRATIONS_DIR
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: TYPEORM_MIGRATIONS_DIR
         - name: TYPEORM_ENTITIES
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: TYPEORM_ENTITIES
         - name: TYPEORM_MIGRATIONS
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: TYPEORM_MIGRATIONS
         - name: TYPEORM_HOST
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: TYPEORM_HOST
         - name: TYPEORM_PORT
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: TYPEORM_PORT
         - name: TYPEORM_USERNAME
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: TYPEORM_USERNAME
         - name: TYPEORM_PASSWORD
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: TYPEORM_PASSWORD      
         - name: TYPEORM_DATABASE
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: TYPEORM_DATABASE        
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: eks-udacity-app
  labels:
    app: eks-udacity-app-be
spec:
  type: LoadBalancer
  selector:
    app:  eks-udacity-app-be
  ports:
      - port: 3030
        targetPort: 3030
        protocol: TCP